In [1]:
from qutip import *

import numpy as np

import matplotlib.pyplot as plt

C:\Users\Daniel Low\Anaconda3\lib\site-packages\qutip\__init__.py:61: UserWarning: Old version of Cython detected: needed 0.29.20, got 0.29.12.
  .format(_cy_require, _Cython.__version__)


In [2]:
"empty Qobj"

print(Qobj())

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]


In [3]:
"5x1 Qobj, ket"

print(Qobj([[1],[2],[3],[4],[5]]))

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [4]:
"1x5 Qobj, bra"

x = np.array([[1, 2, 3, 4, 5]])
print(Qobj(x))

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]


In [5]:
"random 4x4 Qobj. operator"

r = np.random.rand(4, 4)
print(Qobj(r))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.53251351 0.12199693 0.92914106 0.75751987]
 [0.88744248 0.61699752 0.56236208 0.21227791]
 [0.40501624 0.99248487 0.25408272 0.14665363]
 [0.8370895  0.4037503  0.28431417 0.38177923]]


In [6]:
basis(5,3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [7]:
coherent(5,0.5-0.5j)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.7788017 +0.j        ]
 [ 0.38939142-0.38939142j]
 [ 0.        -0.27545895j]
 [-0.07898617-0.07898617j]
 [-0.04314271+0.j        ]]

In [8]:
destroy(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [9]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [10]:
jmat(5/2,'+')

Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[0.         2.23606798 0.         0.         0.         0.        ]
 [0.         0.         2.82842712 0.         0.         0.        ]
 [0.         0.         0.         3.         0.         0.        ]
 [0.         0.         0.         0.         2.82842712 0.        ]
 [0.         0.         0.         0.         0.         2.23606798]
 [0.         0.         0.         0.         0.         0.        ]]

In [11]:
q = destroy(4)

In [12]:
q.dims

[[4], [4]]

In [13]:
q.shape

(4, 4)

In [14]:
q.type

'oper'

In [15]:
q.isherm

False

In [16]:
q.data

<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

In [17]:
x = sigmax()

In [18]:
q + 5

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

In [19]:
x * x

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [20]:
q ** 3

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

In [21]:
x / np.sqrt(2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.         0.70710678]
 [0.70710678 0.        ]]

In [22]:
basis(5, 3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [23]:
basis(5, 3).dag()

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[0. 0. 0. 1. 0.]]

In [24]:
coherent_dm(5, 1)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]

In [25]:
coherent_dm(5, 1).diag()

array([0.36791117, 0.36757705, 0.18523331, 0.05810197, 0.0211765 ])

In [26]:
coherent_dm(5, 1).full()

array([[0.36791117+0.j, 0.36774407+0.j, 0.26105441+0.j, 0.14620658+0.j,
        0.08826704+0.j],
       [0.36774407+0.j, 0.36757705+0.j, 0.26093584+0.j, 0.14614018+0.j,
        0.08822695+0.j],
       [0.26105441+0.j, 0.26093584+0.j, 0.18523331+0.j, 0.10374209+0.j,
        0.06263061+0.j],
       [0.14620658+0.j, 0.14614018+0.j, 0.10374209+0.j, 0.05810197+0.j,
        0.035077  +0.j],
       [0.08826704+0.j, 0.08822695+0.j, 0.06263061+0.j, 0.035077  +0.j,
        0.0211765 +0.j]])

In [27]:
coherent_dm(5, 1).norm()

1.0000000240244786

In [28]:
coherent_dm(5, 1).sqrtm()

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.36791117+5.18703254e-09j 0.36774407-3.01777279e-09j
  0.26105441-2.14225860e-09j 0.14620658-1.19979703e-09j
  0.08826704-7.24334898e-10j]
 [0.36774407-3.01777279e-09j 0.36757705+3.61716863e-09j
  0.26093584-1.20151582e-09j 0.14614018+1.96252184e-10j
  0.08822695+7.36941593e-10j]
 [0.26105441-2.14225860e-09j 0.26093584-1.20151582e-09j
  0.18523331+4.10376998e-09j 0.10374209+1.15537427e-09j
  0.0626306 -1.15778035e-10j]
 [0.14620658-1.19979703e-09j 0.14614018+1.96252184e-10j
  0.10374209+1.15537427e-09j 0.05810197+4.12783000e-10j
  0.035077  +8.24885078e-11j]
 [0.08826704-7.24334898e-10j 0.08822695+7.36941593e-10j
  0.0626306 -1.15778035e-10j 0.035077  +8.24885078e-11j
  0.0211765 +1.54633081e-10j]]

In [29]:
coherent_dm(5, 1).tr()

0.9999999999999999

In [30]:
(basis(4, 2) + basis(4, 1)).unit()

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]